project_path = "C:\\Repository\\python\\robot\\sonataservices.com"
screenshot_path = "C:\\Repository\\python\\robot\\sonataservices.com\\screenshot"
site_url = "https://sonataservices.com"
browser = "chrome"
twitter_status = "//*[@id='status']"
twitter_username_input = "//*[@id='username_or_email']"
twitter_password_input = "//*[@id='password']"
twitter_login_button = "//*[@id='update-form']/div[3]/fieldset[2]/input"
twitter_submit = "//*[@id='update-form']/div[3]/fieldset/input"
twitter_username = "dany_itt@hotmail.com"
twitter_password = "M1P@$$w0rd"

name = "James Wilson"
email_address = "daniel.perez@sonatasmx.com"
phone_number = "6191234567"
company = "Sonata Services MX"
message = "Automation Testing, please ignore"

desktop = "desktop"
portrait = "portrait"
landscape = "landscape"